### ISSUE TITLE
gratton-coles ocular correction

### ISSUE THREAD

**Issue by DT83** [NOCIONS/letswave6#114]
the gratton-coles correction seems not to work as after the correction (both if it is done as a first step or after the epoched data) I have epochs with still large ocular artifact or that become of a larger amplitude as the original file

Emanuel

**Comment by hughherald** [comment]
After checking your data, I found the Gratton and Coles's ocular artifact remove method works well after the bandpass filtering, but fails before the bandpass filter. 

The reason is that there is a high frequency artifact around 0s, which shows very high correlation between the Fp1 and the other channels. This artifact makes the problem for ocular artifact removement, since Gratton and Coles's method are based on removing correlation between channels. Hence, after bandpass filtering, the high frequency artifact around 0s at channel Fp1 is removed,  Gratton and Coles's method can works correctly.
