### ISSUE TITLE
Figure generation - separate waves

### ISSUE THREAD

**Issue by EVale** [NOCIONS/letswave6#123]
Dear Andre',

I was wondering whether there is a way to generate a figure (from figures > wave figure) that allow to have separate waves in separate graphs (like in multiviewer > selection of epochs) rather than overlapping superimposed waves in one figures.

Cheers,

e

**Comment by amouraux** [comment]
Wishlist for Letswave 7 ;-)
On 13 Mar 2017, at 11:22, EVale <notifications@github.com<mailto:notifications@github.com>> wrote:


Dear Andre',

I was wondering whether there is a way to generate a figure (from figures > wave figure) that allow to have separate waves in separate graphs (like in multiviewer > selection of epochs) rather than overlapping superimposed waves in one figures.

Cheers,

e
